-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Extra autostart processes

-- exec-once = uwsm-app -- my-service

-- exec-once = chromium



-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("omarchy-launch-browser")
    hl.exec_cmd("sleep 2.5; ghostty")
end)
