-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Application bindings

hl.bind("SUPER + ALT + RETURN", hl.dsp.exec_cmd("uwsm-app -- xdg-terminal-exec --dir=\"$(omarchy-cmd-terminal-cwd)\" tmux new"))

local terminal = "uwsm-app -- os.getenv(\"TERMINAL\")"

-- $browser = chromium

local browser = "omarchy-launch-browser"

hl.bind("SUPER + RETURN", hl.dsp.exec_cmd("uwsm-app -- " .. os.getenv("TERMINAL") .. " --working-directory=\"$(omarchy-cmd-terminal-cwd)\""))

hl.bind("SUPER + SHIFT + RETURN", hl.dsp.exec_cmd("omarchy-launch-browser"))

hl.bind("SUPER + SHIFT + F", hl.dsp.exec_cmd("uwsm-app -- nautilus --new-window"))

hl.bind("SUPER + ALT + SHIFT + F", hl.dsp.exec_cmd("uwsm-app -- nautilus --new-window \"$(omarchy-cmd-terminal-cwd)\""))

hl.bind("SUPER + B", hl.dsp.exec_cmd("omarchy-launch-browser"))

hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("omarchy-launch-browser --private"))

hl.bind("SUPER + M", hl.dsp.exec_cmd("omarchy-launch-or-focus spotify"))

hl.bind("SUPER + N", hl.dsp.exec_cmd("omarchy-launch-editor"))

-- bindd = SUPER SHIFT, T, Activity, exec, $terminal -e btop

hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("uwsm-app -- " .. os.getenv("TERMINAL") .. " -e lazydocker"))

-- bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus signal "uwsm-app -- signal-desktop"

hl.unbind("SUPER" .. " + " .. "O")

hl.bind("SUPER + O", hl.dsp.exec_cmd("omarchy-launch-or-focus \"^obsidian$\" \"uwsm-app -- obsidian -disable-gpu --enable-wayland-ime\""))

-- bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

-- If your web app url contains #, type it as ## to prevent hyperland treat it as comments

hl.bind("SUPER + A", hl.dsp.exec_cmd("omarchy-launch-webapp \"https://chatgpt.com\""))

hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("omarchy-launch-webapp \"https://claude.ai/new\""))

-- bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"

-- bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"

-- bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"

-- bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

-- bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"

-- bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"

-- bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

-- Overwrite existing bindings, like putting Omarchy Menu on Super + Space

-- unbind = SUPER, SPACE

-- bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

hl.unbind("SUPER" .. " + " .. "K")

hl.unbind("SUPER" .. " + " .. "J")

hl.unbind("SUPER" .. " + " .. "P")

hl.unbind("SUPER" .. " + " .. "mouse_down")

hl.unbind("SUPER" .. " + " .. "mouse_up")

hl.unbind("SUPER + SHIFT" .. " + " .. "SPACE")

hl.unbind("SUPER + SHIFT + CTRL" .. " + " .. "SPACE")

hl.unbind("SUPER" .. " + " .. "BACKSPACE")

hl.unbind("SUPER + SHIFT" .. " + " .. "BACKSPACE")

-- Walker

hl.unbind("SUPER" .. " + " .. "SPACE")

hl.bind("SUPER + D", hl.dsp.exec_cmd("omarchy-launch-walker"))

-- Close Window

hl.unbind("SUPER" .. " + " .. "W")

hl.bind("SUPER + Q", hl.dsp.window.close())

-- Window Navigation

hl.unbind("SUPER" .. " + " .. "LEFT")

hl.unbind("SUPER" .. " + " .. "RIGHT")

hl.unbind("SUPER" .. " + " .. "UP")

hl.unbind("SUPER" .. " + " .. "DOWN")

hl.unbind("SUPER + SHIFT" .. " + " .. "LEFT")

hl.unbind("SUPER + SHIFT" .. " + " .. "RIGHT")

hl.unbind("SUPER + SHIFT" .. " + " .. "UP")

hl.unbind("SUPER + SHIFT" .. " + " .. "DOWN")

hl.unbind("SUPER" .. " + " .. "L")

hl.unbind("super" .. " + " .. "G")

hl.bind("SUPER + H", hl.dsp.focus({ direction = "left" }))

hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }))

hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }))

hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }))

hl.bind("SUPER + SHIFT + H", hl.dsp.window.swap({ direction = "left" }))

hl.bind("SUPER + SHIFT + L", hl.dsp.window.swap({ direction = "right" }))

hl.bind("SUPER + SHIFT + K", hl.dsp.window.swap({ direction = "up" }))

hl.bind("SUPER + SHIFT + J", hl.dsp.window.swap({ direction = "down" }))

-- Captures

hl.unbind("PRINT")

hl.unbind("SHIFT" .. " + " .. "PRINT")

hl.unbind("ALT" .. " + " .. "PRINT")

hl.unbind("SUPER" .. " + " .. "PRINT")

hl.bind("SUPER + Z", hl.dsp.exec_cmd("omarchy-cmd-screenshot smart clipboard"))

hl.bind("SUPER + SHIFT + Z", hl.dsp.exec_cmd("omarchy-cmd-screenshot"))

hl.bind("SUPER + ALT + Z", hl.dsp.exec_cmd("omarchy-menu screenrecord"))

hl.bind("SUPER + SHIFT + ALT + Z", hl.dsp.exec_cmd("pkill hyprpicker || hyprpicker -a"))
