-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "omarchy-lock-screen",
        -- lock screen and 1password
        before_sleep_cmd = "loginctl lock-session",
        -- lock before suspend.
        after_sleep_cmd = "sleep 1 && hyprctl dispatch dpms on",
        -- delay for PAM readiness, then turn on display.
        inhibit_sleep = 3,
        -- wait until screen is locked
    },
})

hl.config({
    listener = {
        timeout = 150,
        -- 2.5min
        on_timeout = "pidof hyprlock || omarchy-launch-screensaver",
        -- start screensaver (if we haven't locked already)
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 151,
        -- 5min
        on_timeout = "loginctl lock-session",
        -- lock screen when timeout has passed
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 330,
        -- 5.5min
        on_timeout = "brightnessctl -sd *::kbd_backlight set 0",
        -- save state and turn off keyboard backlight
        on_resume = "brightnessctl -rd *::kbd_backlight",
        -- restore keyboard backlight
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 330,
        -- 5.5min
        on_timeout = "hyprctl dispatch dpms off",
        -- screen off when timeout has passed
        on_resume = "hyprctl dispatch dpms on && brightnessctl -r",
        -- screen on when activity is detected
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output
