-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Control your input devices

-- See https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        -- Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
        -- kb_layout = us,dk,eu
        kb_layout = "us",
        kb_options = "compose:caps",
        -- ,grp:shifts_toggle
        float_switch_override_focus = 0,
        force_no_accel = true,
        accel_profile = "flat",
        follow_mouse = 2,
        -- Change speed of keyboard repeat
        repeat_rate = 20,
        repeat_delay = 200,
        -- Start with numlock on by default
        numlock_by_default = false,
        -- Increase sensitivity for mouse/trackpad (default: 0)
        -- sensitivity = 0.35
        touchpad = {
            -- Use natural (inverse) scrolling
            -- natural_scroll = true
            -- Use two-finger clicks for right-click instead of lower-right corner
            -- clickfinger_behavior = true
            -- Control the speed of your scrolling
            scroll_factor = 0.4,
        },
    },
})

-- Scroll nicely in the terminal

-- windowrule = scrolltouchpad 1.5, class:(Alacritty|kitty)

-- windowrule = scrolltouchpad 0.2, class:com.mitchellh.ghostty

hl.window_rule({
    name  = "windowrule-ghostty",
    match = {
        class = "com.mitchellh.ghostty",
    },
    scroll_touchpad = 0.2,
})

-- Enable touchpad gestures for changing workspaces

-- See https://wiki.hyprland.org/Configuring/Gestures/

-- gesture = 3, horizontal, workspace
