-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Change the default Omarchy look'n'feel

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        -- No gaps between windows
        gaps_in = 0,
        gaps_out = 0,
        allow_tearing = true,
        -- Use master layout instead of dwindle
        -- layout = master
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        -- Use round window corners
        -- rounding = 8
        active_opacity = 1,
        inactive_opacity = 1,
        fullscreen_opacity = 1,
        shadow = {
            enabled = false,
        },
        blur = {
            enabled = false,
        },
    },
})

hl.config({
    animations = {
        enabled = false,
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#layout

hl.config({
    layout = {
        -- Avoid overly wide single-window layouts on wide screens
        -- single_window_aspect_ratio = 1 1
    },
})

hl.window_rule({
    name  = "windowrule-opaque",
    match = {
        title = ".*",
    },
    opaque = true,
})
