-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Monitors/

-- List current monitors and resolutions possible: hyprctl monitors

-- Format: monitor = [port], resolution, position, scale

-- Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.

-- env = GDK_SCALE,2

-- monitor=,highrr,0x0,1

-- Good compromise for 27" or 32" 4K monitors (but fractional!)

-- env = GDK_SCALE,1.75

-- monitor=,preferred,auto,1.666667

-- Straight 1x setup for low-resolution displays like 1080p or 1440p

hl.env("GDK_SCALE", 1)

hl.monitor({
    output   = "",
    mode     = "2560x1440@144",
    position = "0x0",
    scale    = 1,
})

-- Example for Framework 13 w/ 6K XDR Apple display

-- monitor = DP-5, 6016x3384@60, auto, 2

-- monitor = eDP-1, 2880x1920@120, auto, 2
